# Generated by Django 4.1 on 2023-01-08 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Role',
        ),
    ]
